//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace New_CA2_Assignment
{
    using System;
    using System.Collections.Generic;
    
    public partial class bmaintenance
    {
        public string Sno { get; set; }
        public string Maintenance_Date { get; set; }
        public string Service_Provider_Stats { get; set; }
        public string Equipment_Down_Time { get; set; }
        public string Cost_of_maintenance { get; set; }
        public string Maintenance_last_six_month { get; set; }
    }
}
