//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace New_CA2_Assignment
{
    using System;
    using System.Collections.Generic;
    
    public partial class Component
    {
        public string Id { get; set; }
        public string Component_Number { get; set; }
        public string Name { get; set; }
        public string Replacement_Date { get; set; }
        public string Cost { get; set; }
    }
}
