//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace New_CA2_Assignment
{
    using System;
    using System.Collections.Generic;
    
    public partial class Name_of_maintenance_Company
    {
        public int Id { get; set; }
        public string Name_of_the_Company { get; set; }
        public string Contact_Person_Name { get; set; }
        public string Contact_Person_Telephone { get; set; }
        public string Cost { get; set; }
        public string Address { get; set; }
    }
}
