//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace New_CA2_Assignment
{
    using System;
    using System.Collections.Generic;
    
    public partial class Qualified_employees
    {
        public int Id { get; set; }
        public string Social_Security_Number { get; set; }
        public string Name { get; set; }
        public string Department { get; set; }
        public string Cost { get; set; }
        public string Contact_Numbet { get; set; }
    }
}
