//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace New_CA2_Assignment
{
    using System;
    using System.Collections.Generic;
    
    public partial class Services_by_a_Company
    {
        public int Sno { get; set; }
        public string Name_of_the_Company { get; set; }
        public string Number_of_services_Performed { get; set; }
        public string Telephone_Number { get; set; }
        public string Contact_Number { get; set; }
    }
}
