//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace New_CA2_Assignment
{
    using System;
    using System.Collections.Generic;
    
    public partial class Username
    {
        public string User_id { get; set; }
        public string Forename { get; set; }
        public string Surname { get; set; }
        public string Username1 { get; set; }
        public string Password { get; set; }
        public int Access_Level { get; set; }
    }
}
